export const theme = `
:root{color-scheme:light}body{margin:0;background:#f5f7fc;color:#132451;font:16px/1.6 system-ui,-apple-system,sans-serif}
*{box-sizing:border-box}button,input{font:inherit}button,a,input{ -webkit-tap-highlight-color:transparent}
.shell{max-width:1120px;margin:auto;padding:28px 32px 70px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:24px;padding-bottom:24px;border-bottom:1px solid #dfe5f2}
.brand{font-weight:800;font-size:23px;letter-spacing:-1px;color:#132451;text-decoration:none}.brand:before{content:'◈';color:#3f7c60;margin-right:10px;font-size:28px}
.nav{display:flex;align-items:center;gap:26px}.nav a{color:#576580;text-decoration:none;font-size:14px}.nav a:hover{color:#132451}.btn{border:1px solid #d1daef;border-radius:9px;padding:10px 18px;background:transparent;color:#163477;cursor:pointer;font-weight:650;font-size:14px;transition:background .15s,transform .15s}.btn:hover{background:#eaf0ff;transform:translateY(-1px)}
.hero{padding:66px 0 40px;max-width:810px}.eyebrow{text-transform:uppercase;letter-spacing:2.5px;font-size:11px;font-weight:750;color:#4060a4;display:block}.hero h1{font-size:clamp(38px,5vw,64px);line-height:1.08;font-weight:650;letter-spacing:-2.8px;margin:20px 0}.hero p{font-size:18px;color:#62718c;max-width:610px}.badge{display:inline-block;background:#fff1c5;color:#815e08;padding:5px 11px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:1px}
.playground{display:grid;grid-template-columns:1fr 1fr;gap:22px}.card{border:1px solid #e0e6f2;border-radius:18px;padding:28px;background:#ffffff;position:relative;overflow:hidden}.card h2{font-size:23px;letter-spacing:-.6px;margin:14px 0 8px}.muted{font-size:14px;color:#687a97;margin:0 0 25px}.step{color:#5476b3;font-size:12px;font-weight:700;letter-spacing:2px}.field-label{display:block;font-size:12px;font-weight:650;margin:20px 0 8px;color:#576a8d}
.text-input{width:100%;border:1px solid #d5dff1;border-radius:9px;padding:13px 16px;color:#172e60;background:white;outline:none}.text-input:focus{border-color:#3769ce;box-shadow:0 0 0 3px #3769ce18}.greeting{display:block;color:#1d4fab;font-size:26px;letter-spacing:-.8px;margin-top:24px;overflow-wrap:anywhere}.counter-card{background:#102c76;color:#fff;border:0}.counter-card .step{color:#f6cd58}.counter-card .muted{color:#b9c9ec}.counter{display:block;font-size:88px;line-height:1.2;letter-spacing:-5px;color:#ffcf4a;margin:14px 0 23px;font-weight:550}.counter-card .btn{color:#152650;background:#ffcf4a;border-color:#ffcf4a;min-width:145px}.counter-card .btn:hover{background:#ffdf7c}.counter-card:after{content:'+';font-size:240px;position:absolute;right:12px;top:10px;line-height:1;color:#ffffff06;pointer-events:none}
.footer{display:flex;justify-content:space-between;gap:18px;color:#7484a1;font-size:12px;margin-top:30px}.footer span:first-child:before{content:'●';color:#3c75ce;margin-right:8px}.flow{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.flow .card{padding:25px}.flow p{font-size:14px;color:#607397}.note{font-size:14px;color:#607397;margin-top:25px}
.source-panel{position:fixed;inset:24px;z-index:9000;background:#101e3c;color:#e4ecff;border:1px solid #3b527c;border-radius:16px;box-shadow:0 24px 100px #10251a60;display:flex;flex-direction:column;padding:22px}.source-panel[hidden]{display:none}.source-header{display:flex;justify-content:space-between;align-items:center;gap:16px}.source-header h2{font-size:17px;margin:0}.source-header .btn{color:#e4ecff;border-color:#5671a1}.source-panel pre{overflow:auto;white-space:pre;tab-size:2;font:13px/1.75 ui-monospace,SFMono-Regular,monospace;flex:1;margin-bottom:0}.source-caption{font-size:12px;color:#a0b4db}
.gramlot-inspector-launcher{position:fixed!important;bottom:22px!important;right:22px!important;width:48px!important;height:48px!important;border-radius:50%!important;background:#102c76!important;color:white!important;border:1px solid #6c87c1!important;box-shadow:0 5px 20px #1c392630;font-size:0!important;z-index:9500;padding:0!important;margin:0!important}.gramlot-inspector-launcher:before{content:'⌕';font:23px system-ui;color:#ffcf4a}.gramlot-inspector-launcher:hover{background:#244a98!important}
button:focus-visible,a:focus-visible{outline:3px solid #4c7fe6;outline-offset:4px}
@media(max-width:650px){.shell{padding:18px 20px 85px}.topbar{gap:12px;flex-wrap:wrap}.nav{gap:16px}.hero{padding:40px 0 24px}.hero h1{letter-spacing:-1.5px}.playground,.flow{grid-template-columns:1fr}.card{padding:24px}.footer{flex-direction:column;gap:3px}.source-panel{inset:10px;padding:16px}.source-caption{display:none}}
[hidden]{display:none!important}.brand{display:flex;align-items:center;gap:12px;letter-spacing:-.8px}.brand:before{display:none}.brand img{display:block;object-fit:contain;border-radius:14px;background:white}.brand strong{display:block;font-size:26px;line-height:1.1}.brand-subtitle{display:block;font-size:12px;font-weight:500;letter-spacing:0;color:#607397;margin-top:6px}.nav-tab{border:0;background:transparent;color:#53698d;padding:10px 4px;cursor:pointer;font-size:13px}.nav-tab:hover{color:#174bb5}.source-button{background:#1647aa;color:white;border-color:#1647aa;box-shadow:0 4px 12px #1647aa18}.source-button:hover{background:#245cc3}.hero h1{max-width:720px}.gramlot-inspector-launcher:before{font-size:34px}.topbar{flex-wrap:wrap}.nav{flex-wrap:wrap;gap:18px}
@media(max-width:650px){.brand{width:100%}.nav{width:100%;justify-content:space-between;gap:9px}.brand img{width:56px;height:56px}.brand-subtitle{font-size:12px}.hero{padding-top:30px}.hero h1{font-size:40px}.shell{padding-top:20px}}
`;
